### ISSUE TITLE
Product sorting not working anymore

### ISSUE THREAD

**Issue by jeroentiem** [swissup/module-search-mysql-legacy#16]
After i select the mysql-legacy option the category product sorting is not working anymore, when i switch to elasticsearch 7 it's working again. I don't want to use es so if there is a solution for this.

**Comment by iloa08** [comment]
Same here, waiting for any solution, thank you.

**Comment by 0m3r** [comment]
I can't reproduce it on my Magento instance.

https://github.com/swissup/module-search-mysql-legacy/assets/412612/49e54c95-b084-4900-95de-dd07cf18bb49

![Знімок екрана з 2023-05-23 14-21-48](https://github.com/swissup/module-search-mysql-legacy/assets/412612/fb65194d-0123-41e8-9072-5f7d406fcb97)

Maybe you guys @jeroentiem  @iloa08 use some third-party extensions for layered navigation. Give me more information plz

**Comment by iloa08** [comment]
Thanks for watching.
Could you do the same by adding special-price please ?
(moreover, we can't see price of article on your video)

**Comment by 0m3r** [comment]
What do you mean? Do you mean order by special price or product with special prices? Please send me your detailed explanation.

P.S. Sort by pricing work fine for me.

https://github.com/swissup/module-search-mysql-legacy/assets/412612/5fcbc081-bec4-414a-b045-3dc2153dbd44

**Comment by iloa08** [comment]
Sorry for my english, so could you try to sort by price when you have special price in your listing.

**Comment by 0m3r** [comment]
Work fine for me 
![Знімок екрана з 2023-05-23 15-56-10](https://github.com/swissup/module-search-mysql-legacy/assets/412612/fa9f959e-a7b5-426c-9d5a-aba3fba1c2f6)

p.s. Don't forget to run re-index after adding a special price to a product 
```
bin/magento indexer:reindex catalog_product_price
```

**Comment by iloa08** [comment]
Could you please try with more articles with different discount.

Maybe a problem with tax+special price.

**Comment by 0m3r** [comment]
Please provide step-by-step instructions to reproduce it.

**Comment by iloa08** [comment]
Could you try with only special prices in the listing ?

Here are some examples for my part  :
OK - no special price : https://www.cycles-zanet.com/atelier/outillage.html
OK - just one special price : https://www.cycles-zanet.com/vtc-velos-ville/vtc-electriques.html
OK - special prices : https://www.cycles-zanet.com/electronique.html
NOT OK : only special prices : https://www.cycles-zanet.com/promotions.html
NOT OK - special prices : https://www.cycles-zanet.com/bonneterie/casques.html

Thanks.

**Comment by 0m3r** [comment]
Unfortunately, I can't reproduce it.


https://github.com/swissup/module-search-mysql-legacy/assets/412612/14e88e9a-d506-4edc-8285-130864c38f8c


-  your store uses a custom "special price" attribute
-  you forget to run bin/magento index:reindex
- you use a custom third-party module for navigation

**Comment by jeroentiem** [comment]
I'm using Amasty layered navigation. Please use Position for sorting.

**Comment by iloa08** [comment]
_your store uses a custom "special price" attribute_ : no, the special price is the special price from MAGENTO 2 (class price-container price-final_price tax weee)
_you forget to run bin/magento index:_ reindex : no reindex is ok (check it one more time)
_you use a custom third-party module for navigation :_ this module does not change the order - even if this module is uninstall the problem is still here

You don't have try with only special prices in the listing (all products with a special price - with different discount)

Thank you.

**Comment by 0m3r** [comment]
@iloa08 you need to debug it by yourself because I can't reproduce it.
Find where your product collection apply sort params - Magento\Catalog\Block\Product\ProductList\Toolbar::setCollection
what collection object uses var_dump(get_class($collection));
in my case, it's - Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection

@jeroentiem Sorry I don't support Amasty extensions, try to contact Amasty team

**Comment by pointia** [comment]
@0m3r did you try the module on 2.4.8-p3. Here we have the Problem that the product sorting is not working. You can have a look into the behaviour right here: https://shop.thermochema.at/spezialprodukte/entkalker.html?product_list_order=position&product_list_dir=desc

I tried to debug it but since the sort order is only provided by the returned id I was unable to get it working again.

I can see that the Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::apply orders the result by the returned entity_id but I don't know what I have to do to get the sorting corect in the legacy sql statement to return the items in the correct order

**Comment by 0m3r** [comment]
> [@0m3r](https://github.com/0m3r) did you try the module on 2.4.8-p3. Here we have the Problem that the product sorting is not working. You can have a look into the behaviour right here: https://shop.thermochema.at/spezialprodukte/entkalker.html?product_list_order=position&product_list_dir=desc
> 
> I tried to debug it but since the sort order is only provided by the returned id I was unable to get it working again.
> 
> I can see that the Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplier::apply orders the result by the returned entity_id but I don't know what I have to do to get the sorting corect in the legacy sql statement to return the items in the correct order

Hi @pointia,

Thanks for the detailed report and debugging!

You're correct that `SearchResultApplier::apply()` orders results by returned `entity_id` order, but the **root cause** is that MySQL search results don't include user-defined sort fields like `position`.

### The Problem

1. **Magento Search Request API doesn't pass sort order to search engine**
   - `RequestInterface` only contains: query, filters, size, offset
   - Sort order is applied **after** search results are returned

2. **In Magento 2.4.8, SearchResultApplier forces ORDER BY FIELD()**
   - It locks the result order based on search engine response
   - User sort order can't be re-applied afterward

3. **MySQL search results don't contain `position` field**
   - Search engine returns: `[entity_id, relevance]`
   - Position is stored separately in `catalog_category_product_index`

### This is a Magento 2.4.8 Regression

In earlier versions, collection could re-apply sort order after search. In 2.4.8, `SearchResultApplier` breaks this by forcing `ORDER BY FIELD()`.

### Workaround Options

#### Option 1: Disable SearchResultApplier (Risky)

```xml
<!-- di.xml -->
<preference for="Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\SearchResultApplierInterface"
            type="Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection\DefaultFilterStrategy"/>
```

**Warning:** This may break other functionality.

#### Option 2: Plugin to Remove FIELD() Order

Create a plugin to remove forced order when custom sort is present:

```php
<?php
namespace YourVendor\YourModule\Plugin;

class RemoveFieldOrder
{
    public function afterLoad(
        \Magento\CatalogSearch\Model\ResourceModel\Fulltext\Collection $collection
    ) {
        $select = $collection->getSelect();
        $orders = $select->getPart(\Magento\Framework\DB\Select::ORDER);
        
        if (count($orders) > 1) {
            // Remove FIELD() order, keep user sort
            $filteredOrders = array_filter($orders, function($order) {
                return strpos((string)$order[0], 'FIELD') === false;
            });
            
            if ($filteredOrders) {
                $select->reset(\Magento\Framework\DB\Select::ORDER);
                foreach ($filteredOrders as $order) {
                    $select->order($order);
                }
            }
        }
        
        return $collection;
    }
}
```

#### Option 3: Report to Magento

This is a **Magento Core regression**. The correct fix should be in `SearchResultApplier` to check if collection already has sort order before forcing `ORDER BY FIELD()`.

### Proper Fix (for Magento Core)

```php
// In SearchResultApplier::apply()
public function apply()
{
    // ... existing code ...
    
    // BEFORE forcing FIELD() order:
    $existingOrders = $this->collection->getSelect()->getPart(Select::ORDER);
    if (!empty($existingOrders)) {
        // Don't override user sort order
        return;
    }
    
    // THEN apply FIELD() order
    // ... rest of code ...
}
```

### Recommendation

**For now:** Use Option 2 (plugin) as a temporary workaround.

**Long-term:** Report this regression to Magento Core: https://github.com/magento/magento2/issues

This is NOT a bug in `module-search-mysql-legacy` — the search engine correctly returns filtered product IDs. The problem is in how Magento 2.4.8's `SearchResultApplier` handles those results.

---

**Note:** I may add a built-in fix for this in a future release, but it requires careful testing to avoid breaking other functionality.
